name: geo
favicon: null
layout_spectrum: 0.38392040226608515
typography_spectrum: 0.48198358132503927
title: GeoSite
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.31607450381852686
  lightness: 0.3125
  saturation: 0.8945431092288345
  rhythmicContrast: 0.9623833987861872
purpose: []
